name = "Aya Neo Power Tools"
version = "1.0.0"
link = "TODO"
source = "TODO"

[author]
name = "Derek J. Clark"
link = "TODO"

[entrypoints]

	[entrypoints.desktop]
	library = true
	menu = false

	[entrypoints.deck]
	library = false
	menu = false
